### ISSUE TITLE
service json data or backend api of app

### ISSUE THREAD

**Issue by yahi99** [DIEUDONNE-DENGUN/DenPlaces#1]
Dear sir i am working on the project like this. First of all thanks for sharing this app. I am starter for ionic app so Where is backend data api or json data of this app for testing?

**Comment by DIEUDONNE-DENGUN** [comment]
Glad you are interested in the project. Actually, there is currently no backend service to scale and better manage the app from the server end. However, it is  being powered by Google Maps through its Places API service which literally acts as backend for providing data to the app. If you are solely interested in scaling the app at the server side, you can hit me on LinkedIn (@Dieudonne Dengun) for private conversation for such directives. Thanks
